name: Test

on:
  pull_request:
  pull_request_target:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - shell: bash
        run: |
          git log
          git status
          git show @
