name: Test

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Add Label
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
      - shell: bash
        run: |
          echo "Secret: ${{ secrets.FOO }}"
          echo "Variable: ${{ vars.BAR }}"
          git log
          git status
          git show @
